# 1. directory
root_path: "/home/chenyu/SSMIS/data/ACDC"
res_path: "./results/ACDC"
# random seed
seed: 2025
test_interval_ep: 2

model1: unet
model2: res18unet
alpha: 1.0
# 2. training
labeled_num: 3               # TBD:   3, 7, 14
max_iterations: 30000
base_lr: 0.01
batch_size: 24               # ws 36
labeled_bs: 12
poly: True

at_weight: 10

# 3. supervision
consistency: 2.0
consistency_rampup: 50

